# -*- coding: utf-8 -*-
"""object_detection_using_Machine_Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beC_uZdv8jDf2Dt_93qGtIGys4ETS7a0
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import cvlib as cv
from cvlib.object_detection import draw_bbox
from numpy.lib.polynomial import poly

!pip install cvlib

image = cv2.imread("image.jpeg")
plt.imshow(image)
plt.show()
#Detect common objects using detect_common_objects function of cv2
box, label, count = cv.detect_common_objects(image)

#Draw the box around the detected objects and assign labels
output = draw_bbox(image, box, label, count)

#Dispay the image
plt.imshow(output)
plt.show()

#Display the common objects detected
print("Number of cars in this image are " +str(label.count('car')))
print("Number of trucks in this image are " +str(label.count('truck')))

